=== 52North/pygeoapi-docker-backend/schemas/tms/2.0/json/tileSet.json
{
	"$schema": "https://json-schema.org/draft/2019-09/schema",
	"title": "Tile Set Metadata",
	"description": "A resource describing a tileset based on the OGC TileSet Metadata Standard. At least one of the 'TileMatrixSet',  or a link with 'rel' http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
	"type": "object",
	"required": ["dataType", "crs"],
	"properties":
	{
		"title": {
			"description": "A title for this tileset",
			"type": "string"
		},
		"description": {
			"description": "Brief narrative description of this tile set",
			"type": "string"
		},
		"keywords": {
			"description": "keywords about this tileset",
			"type": "array",
			"items":
			{
				"type": "string"
			}
		},
		"version": {
			"description": "Version of the Tile Set. Changes if the data behind the tiles has been changed",
			"type": "string"
		},
		"pointOfContact": {
			"description": "Useful information to contact the authors or custodians for the Tile Set",
			"type": "string"
		},
		"attribution": {
			"description": "Short reference to recognize the author or provider",
			"type": "string"
		},
		"license": {
			"description": "License applicable to the tiles",
			"type": "string"
		},
		"accessConstraints": {
			"description": "Restrictions on the availability of the Tile Set that the user needs to be aware of before using or redistributing the Tile Set",
			"type": "string",
			"default": "unclassified",
			"enum": ["unclassified", "restricted", "confidential", "secret", "topSecret"]
		},
		"mediaTypes": {
			"description": "Media types available for the tiles",
			"type": "array",
			"items":
			{
				"type": "string"
			}
		},
		"dataType": { "allOf": [
			{ "description": "Type of data represented in the tileset" },
			{ "$ref": "dataType.json" }
		] },
		"tileMatrixSetLimits": {
			"description": "Limits for the TileRow and TileCol values for each TileMatrix in the tileMatrixSet. If missing, there are no limits other that the ones imposed by the TileMatrixSet. If present the TileMatrices listed are limited and the rest not available at all",
			"type": "array",
			"items":
			{
				"$ref": "tileMatrixLimits.json"
			}
		},
		"crs": { "allOf": [
			{ "description": "Coordinate Reference System (CRS)" },
			{ "$ref": "crs.json" }
		] },
		"epoch": {
			"description": "Epoch of the Coordinate Reference System (CRS)",
			"type": "number"
		},
		"boundingBox": { "allOf": [
         { "description": "Minimum bounding rectangle surrounding the tile matrix set, in the supported CRS" },
         { "$ref": "2DBoundingBox.json" }
		] },
		"created": { "allOf": [
			{ "description": "When the Tile Set was first produced" },
			{ "$ref": "timeStamp.json" }
		] },
		"updated": { "allOf": [
			{ "description": "Last Tile Set change/revision" },
			{ "$ref": "timeStamp.json" }
		] },
		"layers": {
			"minItems": 1,
			"type": "array",
			"items":
			{
				"$ref": "geospatialData.json"
			}
		},
		"style": { "allOf": [
			{ "description": "Style involving all layers used to generate the tileset" },
			{ "$ref": "style.json" }
		] },
		"centerPoint":
		{ "allOf" : [
			{ "description": "Location of a tile that nicely represents the tileset. Implementations may use this center value to set the default location or to present a representative tile in a user interface" },
			{ "$ref": "tilePoint.json" }
		] },
		"tileMatrixSet":
		{
			"description": "Tile matrix set definition",
			"$ref": "tileMatrixSet.json"
		},
		"tileMatrixSetURI":
		{
			"description": "Reference to a Tile Matrix Set on an official source for Tile Matrix Sets such as the OGC-NA definition server (http://www.opengis.net/def/tms). Required if the tile matrix set is registered on an open official source.",
			"type": "string",
			"format": "uri"
		},
		"links":
		{
			"description": "Links to related resources. Possible link 'rel' values are: 'http://www.opengis.net/def/rel/ogc/1.0/dataset' for a URL pointing to the dataset, 'item' for a URL template to get a tile; 'alternate' for a URL pointing to another representation of the TileSetMetadata (e.g a TileJSON file); 'http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme' for a definition of the TileMatrixSet; 'http://www.opengis.net/def/rel/ogc/1.0/geodata' for pointing to a single collection (if the tileset represents a single collection)",
			"type": "array",
			"items": {
				"$ref": "link.json"
			}
		}
	}
}

=== 52North/pygeoapi-docker-backend/schemas/tms/2.0/json/examples/tileset/map.tiles.WebMercatorQuad.json
{
   "title" : "Daraa map tiles",
   "description" : "Rendered tiles of Daraa, Syria from NSG OpenStreetMap Topographic Data Store",
   "keywords" : [ "Daraa", "Syria", "OpenStreetMap", "NSG", "TDS" ],
   "dataType" : "map",
   "accessConstraints" : "unclassified",
   "crs" : "http://www.opengis.net/def/crs/EPSG/0/3857",
   "epoch" : 2021.33,
   "links" : [
      {
         "rel" : "self",
         "type" : "application/json",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad?f=json"
      },
      {
         "rel" : "alternate",
         "type" : "application/json+vnd.mapbox.tilejson",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad?f=tilejson"
      },
      {
         "rel" : "tiling-scheme",
         "type" : "application/json",
         "href" : "/Daraa/ogcapi/tileMatrixSets/WebMercatorQuad"
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}",
         "templated" : true
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.png",
         "type" : "image/png",
         "templated" : true
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.jpg",
         "type" : "image/jpg",
         "templated" : true
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/map/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.tif",
         "type" : "image/tiff; application=geotiff",
         "templated" : true
      },
      {
         "rel"  : "dataset",
         "href" : "/Daraa/ogcapi"
      }
   ],
   "style" :
   {
      "id" : "topographic",
      "links" : [
         {
            "rel"  : "http://www.opengis.net/def/rel/ogc/1.0/style",
            "href" : "/Daraa/ogcapi/styles/topographic"
         }
      ]
   },
   "layers" : [
      {
         "id" : "Daraa",
         "dataType" : "vector",
         "geometryDimension" : "2",
         "maxTileMatrix" : "17",
         "minScaleDenominator" : 4265.4591676995678,
         "minCellSize" : 1.19432856696,
         "boundingBox" :
         {
            "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
            "lowerLeft" : [ 35, 32 ],
            "upperRight" : [ 37, 33.2671397 ]
         },
         "links" : [
            {
               "rel"  : "http://www.opengis.net/def/rel/ogc/1.0/geodata",
               "href" : "/Daraa/ogcapi/collections/AgricultureSrf"
            }
         ]
      }
   ],
   "tileMatrixSetURI" : "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
   "tileMatrixSetLimits" : [
      { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
      { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
      { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
      { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
      { "tileMatrix" : "4", "minTileRow" : 6, "maxTileRow" : 6, "minTileCol" : 9, "maxTileCol" : 9 },
      { "tileMatrix" : "5", "minTileRow" : 12, "maxTileRow" : 12, "minTileCol" : 19, "maxTileCol" : 19 },
      { "tileMatrix" : "6", "minTileRow" : 25, "maxTileRow" : 25, "minTileCol" : 38, "maxTileCol" : 38 },
      { "tileMatrix" : "7", "minTileRow" : 51, "maxTileRow" : 51, "minTileCol" : 76, "maxTileCol" : 77 },
      { "tileMatrix" : "8", "minTileRow" : 102, "maxTileRow" : 103, "minTileCol" : 152, "maxTileCol" : 154 },
      { "tileMatrix" : "9", "minTileRow" : 205, "maxTileRow" : 207, "minTileCol" : 305, "maxTileCol" : 308 },
      { "tileMatrix" : "10", "minTileRow" : 411, "maxTileRow" : 415, "minTileCol" : 611, "maxTileCol" : 617 },
      { "tileMatrix" : "11", "minTileRow" : 823, "maxTileRow" : 831, "minTileCol" : 1223, "maxTileCol" : 1234 },
      { "tileMatrix" : "12", "minTileRow" : 1646, "maxTileRow" : 1663, "minTileCol" : 2446, "maxTileCol" : 2468 },
      { "tileMatrix" : "13", "minTileRow" : 3292, "maxTileRow" : 3326, "minTileCol" : 4892, "maxTileCol" : 4937 },
      { "tileMatrix" : "14", "minTileRow" : 6584, "maxTileRow" : 6653, "minTileCol" : 9784, "maxTileCol" : 9875 },
      { "tileMatrix" : "15", "minTileRow" : 13169, "maxTileRow" : 13306, "minTileCol" : 19569, "maxTileCol" : 19751 },
      { "tileMatrix" : "16", "minTileRow" : 26339, "maxTileRow" : 26613, "minTileCol" : 39139, "maxTileCol" : 39503 },
      { "tileMatrix" : "17", "minTileRow" : 52679, "maxTileRow" : 53227, "minTileCol" : 78279, "maxTileCol" : 79007 }
   ],
   "boundingBox" :
   {
      "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "lowerLeft" : [ 35, 32 ],
      "upperRight" : [ 37, 33.2671397 ]
   },
   "centerPoint" :
   {
      "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "coordinates" : [ 36.2298413, 32.65020355 ],
      "scaleDenominator" : 17061.8366707982,
      "cellSize" : 4.77731426782,
      "tileMatrix" : "15"
   }
}

=== 52North/pygeoapi-docker-backend/schemas/tms/2.0/json/examples/tileset/tiles.WebMercatorQuad.json
{
   "title" : "Daraa multi-layer vector tiles",
   "description" : "Vector tiles of Daraa, Syria from NSG OpenStreetMap Topographic Data Store",
   "keywords" : [ "Daraa", "Syria", "OpenStreetMap", "NSG", "TDS" ],
   "dataType" : "vector",
   "accessConstraints" : "unclassified",
   "crs" : "http://www.opengis.net/def/crs/EPSG/0/3857",
   "epoch" : 2021.33,
   "links" : [
      {
         "rel" : "self",
         "type" : "application/json",
         "href" : "/Daraa/ogcapi/tiles/WebMercatorQuad?f=json"
      },
      {
         "rel" : "alternate",
         "type" : "application/json+vnd.mapbox.tilejson",
         "href" : "/Daraa/ogcapi/tiles/WebMercatorQuad?f=tilejson"
      },
      {
         "rel" : "tiling-scheme",
         "type" : "application/json",
         "href" : "/Daraa/ogcapi/tileMatrixSets/WebMercatorQuad"
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}",
         "templated" : true
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.json",
         "type" : "application/geo+json",
         "templated" : true
      },
      {
         "rel"  : "item",
         "href" : "/Daraa/ogcapi/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}.mvt",
         "type" : "application/vnd.mapbox-vector-tile",
         "templated" : true
      },
      {
         "rel"  : "dataset",
         "href" : "/Daraa/ogcapi"
      }
   ],
   "layers" : [
      {
         "id" : "AgricultureSrf",
         "dataType" : "vector",
         "geometryDimension" : "2",
         "maxTileMatrix" : "17",
         "minScaleDenominator" : 4265.4591676995678,
         "minCellSize" : 1.19432856696,
         "boundingBox" :
         {
            "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
            "lowerLeft": [35.898213, 32.4633913],
            "upperRight": [36.5614696, 32.8370158]
         },
         "geoDataClasses" : [ "http://example.com/def/geodataclasses/OSMNSGTDS" ],
         "links" : [
            {
               "rel"  : "http://www.opengis.net/def/rel/ogc/1.0/geodata",
               "href" : "/Daraa/ogcapi/collections/AgricultureSrf"
            }
         ],
         "propertiesSchema" :
         {
            "type": "object",
            "properties": {
               "F_CODE" :
               {
                  "title" : "Feature Code",
                  "type" : "string",
                  "enum" : [ "EA010", "EA040", "AM020" ]
               },
               "FFN" : { "type" : "integer" },
               "FCSUBTYPE" :
               {
                  "title" : "Feature subtype",
                  "type" : "integer",
                  "enum" : [ 100380, 100384 ]
               },
               "ZI005_FNA" : { "type" : "string"  }
            }
         }
      },
      {
         "id" : "TransportationGroundCrv",
         "dataType" : "vector",
         "geometryDimension" : "1",
         "maxTileMatrix" : "17",
         "minScaleDenominator" : 4265.4591676995678,
         "minCellSize" : 1.19432856696,
         "boundingBox" :
         {
            "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
            "lowerLeft": [35.9028738, 32.4168138],
            "upperRight": [36.5747694, 33.1424348]
         },
         "geoDataClasses" : [ "http://example.com/def/geodataclasses/OSMNSGTDS" ],
         "links" : [
            {
               "rel"  : "http://www.opengis.net/def/rel/ogc/1.0/geodata",
               "href" : "/Daraa/ogcapi/collections/TransportationGroundCrv"
            }
         ],
         "propertiesSchema" :
         {
            "type": "object",
            "properties" :
            {
               "F_CODE" :
               {
                  "title" : "Feature Code",
                  "type" : "string",
                  "enum" : [ "AN010", "AP010", "AP030", "AQ040" ]
               },
               "FFN" : { "type" : "integer" },
               "FCSUBTYPE" :
               {
                  "title" : "Feature subtype",
                  "type" : "integer",
                  "enum" : [ 100143, 100152, 100161 ]
               },
               "ZI005_FNA" : { "type" : "string"  }
            }
         }
      }
   ],
   "tileMatrixSetURI" : "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
   "tileMatrixSetLimits" : [
      { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
      { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
      { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
      { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
      { "tileMatrix" : "4", "minTileRow" : 6, "maxTileRow" : 6, "minTileCol" : 9, "maxTileCol" : 9 },
      { "tileMatrix" : "5", "minTileRow" : 12, "maxTileRow" : 12, "minTileCol" : 19, "maxTileCol" : 19 },
      { "tileMatrix" : "6", "minTileRow" : 25, "maxTileRow" : 25, "minTileCol" : 38, "maxTileCol" : 38 },
      { "tileMatrix" : "7", "minTileRow" : 51, "maxTileRow" : 51, "minTileCol" : 76, "maxTileCol" : 77 },
      { "tileMatrix" : "8", "minTileRow" : 102, "maxTileRow" : 103, "minTileCol" : 152, "maxTileCol" : 154 },
      { "tileMatrix" : "9", "minTileRow" : 205, "maxTileRow" : 207, "minTileCol" : 305, "maxTileCol" : 308 },
      { "tileMatrix" : "10", "minTileRow" : 411, "maxTileRow" : 415, "minTileCol" : 611, "maxTileCol" : 617 },
      { "tileMatrix" : "11", "minTileRow" : 823, "maxTileRow" : 831, "minTileCol" : 1223, "maxTileCol" : 1234 },
      { "tileMatrix" : "12", "minTileRow" : 1646, "maxTileRow" : 1663, "minTileCol" : 2446, "maxTileCol" : 2468 },
      { "tileMatrix" : "13", "minTileRow" : 3292, "maxTileRow" : 3326, "minTileCol" : 4892, "maxTileCol" : 4937 },
      { "tileMatrix" : "14", "minTileRow" : 6584, "maxTileRow" : 6653, "minTileCol" : 9784, "maxTileCol" : 9875 },
      { "tileMatrix" : "15", "minTileRow" : 13169, "maxTileRow" : 13306, "minTileCol" : 19569, "maxTileCol" : 19751 },
      { "tileMatrix" : "16", "minTileRow" : 26339, "maxTileRow" : 26613, "minTileCol" : 39139, "maxTileCol" : 39503 },
      { "tileMatrix" : "17", "minTileRow" : 52679, "maxTileRow" : 53227, "minTileCol" : 78279, "maxTileCol" : 79007 }
   ],
   "boundingBox" :
   {
      "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "lowerLeft" : [ 35, 32 ],
      "upperRight" : [ 37, 33.2671397 ]
   },
   "centerPoint" :
   {
      "crs" : "http://www.opengis.net/def/crs/OGC/1.3/CRS84",
      "coordinates" : [ 36.2298413, 32.65020355 ],
      "scaleDenominator" : 17061.8366707982,
      "cellSize" : 4.77731426782,
      "tileMatrix" : "15"
   }
}
